"""Public interface for the Online Learning (Hedge / FTRL / FTPL) model.

See `models/layer4_signals_ml/13_online_learning.md` for the full
specification.
"""

from __future__ import annotations

from src.models.online_learning.calibration import (
    MODEL_NAME,
    calibrate,
    calibrate_ftrl,
)
from src.models.online_learning.model import OnlineLearning
from src.models.online_learning.signal import (
    adaptive_eta,
    build_vol_expert_panel,
    clip_normalize_losses,
    cusum_break_detect,
    empirical_regret,
    ewma_vol,
    expert_losses,
    ftpl_sample_action,
    ftrl_dense_theta,
    ftrl_predict,
    ftrl_step,
    ftrl_theta,
    ftrl_update,
    hedge_predict,
    hedge_step,
    initial_ftrl_state,
    initial_hedge_state,
    log_loss,
    realized_vol_target,
    regret_bound_hedge,
    rolling_realized_vol,
    run_hedge_stream,
    safe_log,
    sigmoid,
    sparsity_fraction,
    weight_entropy,
)
from src.models.online_learning.types import (
    VALID_ETA_SCHEDULES,
    VALID_KINDS,
    VALID_LOSS_KINDS,
    EtaSchedule,
    ExpertStream,
    FTRLConfig,
    FTRLFit,
    FTRLState,
    HedgeConfig,
    HedgeFit,
    HedgeState,
    LearnerKind,
    LossKind,
    OnlineLearningInputs,
)

__all__ = [
    "MODEL_NAME",
    "OnlineLearning",
    "VALID_ETA_SCHEDULES",
    "VALID_KINDS",
    "VALID_LOSS_KINDS",
    "EtaSchedule",
    "ExpertStream",
    "FTRLConfig",
    "FTRLFit",
    "FTRLState",
    "HedgeConfig",
    "HedgeFit",
    "HedgeState",
    "LearnerKind",
    "LossKind",
    "OnlineLearningInputs",
    "adaptive_eta",
    "build_vol_expert_panel",
    "calibrate",
    "calibrate_ftrl",
    "clip_normalize_losses",
    "cusum_break_detect",
    "empirical_regret",
    "ewma_vol",
    "expert_losses",
    "ftpl_sample_action",
    "ftrl_dense_theta",
    "ftrl_predict",
    "ftrl_step",
    "ftrl_theta",
    "ftrl_update",
    "hedge_predict",
    "hedge_step",
    "initial_ftrl_state",
    "initial_hedge_state",
    "log_loss",
    "realized_vol_target",
    "regret_bound_hedge",
    "rolling_realized_vol",
    "run_hedge_stream",
    "safe_log",
    "sigmoid",
    "sparsity_fraction",
    "weight_entropy",
]
